export const ALERTS = {
  EXPERIENCE: {
    ADD_EXPERIENCE: 'Experience added successfully!',
    UPDATE_EXPERIENCE: 'Experience updated successfully!',
    DELETE_EXPERIENCE: 'Experience deleted successfully!',
  },
  SKILL: {
    ADD_SKILL: 'Skill added successfully!',
    UPDATE_SKILL: 'Skill updated successfully!',
    DELETE_SKILL: 'Skill deleted successfully!',
  },
  PROJECT: {
    ADD_PROJECT: 'Project added successfully!',
    UPDATE_PROJECT: 'Project updated successfully!',
    DELETE_PROJECT: 'Project deleted successfully!',
  },
  BLOG: {
    ADD_BLOG: 'Blog added successfully!',
    UPDATE_BLOG: 'Blog updated successfully!',
    DELETE_BLOG: 'Blog deleted successfully!',
  },
  BUTTON: {
    ADD_EXPERIENCE: 'Add Experience',
    UPDATE_EXPERIENCE: 'Update Experience',
    ADD_SKILL: 'Add Skill',
    UPDATE_SKILL: 'Update Skill',
    ADD_PROJECT: 'Add Project',
    UPDATE_PROJECT: 'Update Project',
    ADD_BLOG: 'Add Blog',
    UPDATE_BLOG: 'Update Blog',
    DELETE: 'Delete',
    EDIT: 'Edit',
  },
  PAGE_TITLE: {
    ALL_EXPERIENCE: 'All Experience',
    ADD_EXPERIENCE: 'Add New Experience',
    EDIT_EXPEREIENCE: 'Edit experience',
    ALL_SKILL: 'All Skills',
    ADD_SKILL: 'Add Skill',
    EDIT_SKILL: 'Edit Skill',
    ALL_PROJECT: 'All Project',
    ADD_PROJECT: 'Add Project',
    EDIT_PROJECT: 'Edit Project',
    ALL_BLOG: 'All Blog',
    ADD_BLOG: 'Add Blog',
    EDIT_BLOG: 'Edit Blog',
  },
  SOMETHING_WRONG: 'Something went wrong!',
  ERROR_FETCH: 'Error fetching data!!',
  CREATION_PROGRESS: 'Creation in progress...',
  UPDATING_PROGRESS: 'Updating in progress...',
  LOGOUT: 'Logout',
};
